[package]
name = "aoc21"
version = "0.1.0"
authors = ["Olivier Dony <odo@odoo.com>"]
edition = "2018"

[dependencies]
aoc-runner = "0.3"
aoc-runner-derive = "0.3"
counter = ""
lazy_static = ""
num = ""
regex = ""